// src/components/AuthPanel.jsx
import { h } from 'preact'
import { useEffect, useRef, useState } from 'preact/hooks'
import { apiFetch, endpoints, getCreds, setCreds, clearCreds } from '../lib/api'

export default function AuthPanel({ signedIn, onSignedIn, onSignedOut }) {
  const [step, setStep] = useState('phone')
  const [phone, setPhone] = useState('')
  const [imei, setImei] = useState('')
  const [remember, setRemember] = useState(false)
  const [status, setStatus] = useState('')
  const [resendLeft, setResendLeft] = useState(0)
  const resendTimerRef = useRef(null)

  const otpRefs = Array.from({ length: 6 }, () => useRef(null))

  useEffect(() => {
    return () => { if (resendTimerRef.current) clearInterval(resendTimerRef.current) }
  }, [])

  useEffect(() => {
    const creds = getCreds()
    if (creds) {
      setStep('code')
    }
  }, [])

  function startResendCountdown() {
    setResendLeft(30)
    if (resendTimerRef.current) clearInterval(resendTimerRef.current)
    resendTimerRef.current = setInterval(() => {
      setResendLeft((n) => {
        if (n <= 1) { clearInterval(resendTimerRef.current); resendTimerRef.current = null; return 0 }
        return n - 1
      })
    }, 1000)
  }

  function readOtp() {
    return otpRefs.map(r => r.current?.value?.trim() || '').join('')
  }

  function clearOtp() {
    otpRefs.forEach(r => { if (r.current) r.current.value = '' })
  }

  async function sendOtp(isResend = false) {
    try {
      setStatus('')
      const body = isResend && imei ? { phone, imei } : { phone }
      const res = await apiFetch(endpoints.authStart, { method: 'POST', body: JSON.stringify(body) })
      const newImei = res?.imei
      if (!newImei) throw new Error('No IMEI returned')
      setImei(newImei)
      setStep('code')
      clearOtp()
      startResendCountdown()
      setStatus('Code sent')
    } catch (e) {
      setStatus(`Send failed: ${e.message}`)
    }
  }

  async function verify() {
    const code = readOtp()
    if (!phone || !imei || !code) { setStatus('Enter phone and full code'); return }
    try {
      const res = await apiFetch(endpoints.authVerify, { method: 'POST', body: JSON.stringify({ imei, phone, code }) })
      if (!res?.token) throw new Error('No token')
      setCreds({ imei, token: res.token }, remember)
      setStatus('Signed in')
      onSignedIn?.()
    } catch (e) {
      setStatus(`Verify failed: ${e.message}`)
    }
  }

  function logout() {
    clearCreds()
    setStatus('Signed out')
    onSignedOut?.()
    setStep('phone')
  }

  if (signedIn) {
    return (
      <div class="auth-panel">
        <div class="auth-actions">
          <button class="btn secondary" onClick={logout}>Logout</button>
        </div>
        <span class="status">{status}</span>
      </div>
    )
  }

  return (
    <div class="auth-panel">
      <h2>Sign in</h2>
      {step === 'phone' && (
        <div class="auth-step">
          <label>
            Phone
            <input type="tel" placeholder="05XXXXXXXX" inputmode="tel" autocomplete="tel" value={phone} onInput={e => setPhone(e.currentTarget.value)} />
          </label>
          <button class="btn primary" onClick={() => sendOtp(false)}>Send code</button>
        </div>
      )}

      {step === 'code' && (
        <div class="auth-step">
          <p class="muted">Enter the 6-digit code sent to <strong>{phone}</strong></p>
          <div class="otp-grid" role="group" aria-label="One-time code">
            {otpRefs.map((ref, i) => (
              <input key={i} ref={ref} inputmode="numeric" pattern="[0-9]*" maxLength={1} onInput={(e) => {
                e.currentTarget.value = e.currentTarget.value.replace(/\D/g, '').slice(0,1)
                if (e.currentTarget.value && i < otpRefs.length - 1) otpRefs[i+1].current?.focus()
              }} onKeyDown={(e) => {
                if (e.key === 'Backspace' && !e.currentTarget.value && i > 0) otpRefs[i-1].current?.focus()
              }} />
            ))}
          </div>
          <input type="text" readOnly class="visually-hidden" aria-hidden="true" tabIndex={-1} value={imei} />
          <div class="auth-row">
            <label class="remember">
              <input type="checkbox" checked={remember} onChange={(e) => setRemember(e.currentTarget.checked)} /> Remember me
            </label>
          </div>
          <div class="auth-actions">
            <button class="btn primary" onClick={verify}>Verify</button>
            <button class="btn secondary" disabled={resendLeft>0} onClick={() => sendOtp(true)}>Resend</button>
            <span class="muted">{resendLeft>0 ? `You can resend in ${resendLeft}s` : ''}</span>
          </div>
          <div class="auth-links">
            <button class="linklike" type="button" onClick={() => { setImei(''); clearOtp(); setStep('phone') }}>Edit phone</button>
          </div>
        </div>
      )}

      <span class="status">{status}</span>
    </div>
  )
}

// web/src/components/AuthPanel.svelte
<script>
  import { createEventDispatcher, onMount } from 'svelte'
  import { creds, statusLine } from '../stores.js'
  import { startOtp, verifyOtp, setCreds } from '../lib/api.js'

  const dispatch = createEventDispatcher()

  let phone = ''
  let imei = ''
  let code = ['', '', '', '', '', '']
  let remember = false
  let step = 'phone'
  let resendSec = 30
  let resendTimerId = null

  function codeString() { return code.join('').replace(/\D/g, '') }

  function startResendTimer() {
    stopResendTimer()
    let remaining = resendSec
    const tick = () => {
      remaining -= 1
      if (remaining <= 0) stopResendTimer()
      else resendText = `You can resend in ${remaining}s`
    }
    resendText = `You can resend in ${remaining}s`
    resendTimerId = setInterval(tick, 1000)
  }

  function stopResendTimer() {
    if (resendTimerId) clearInterval(resendTimerId)
    resendTimerId = null
    resendText = ''
  }

  let resendText = ''
  let sending = false
  let verifying = false

  async function onSendOtp(isResend = false) {
    if (!phone) { statusLine.set('Enter phone number'); return }
    sending = true
    try {
      const payloadImei = isResend && imei ? imei : undefined
      const res = await startOtp(phone, payloadImei)
      imei = res?.imei || ''
      if (!imei) throw new Error('No IMEI returned')
      statusLine.set('Code sent')
      code = ['', '', '', '', '', '']
      step = 'code'
      startResendTimer()
    } catch (e) {
      statusLine.set(`Send failed: ${e.message}`)
    } finally {
      sending = false
    }
  }

  async function onVerify() {
    const c = codeString()
    if (!phone || !imei || !c) { statusLine.set('Enter phone and full code'); return }
    verifying = true
    try {
      const res = await verifyOtp(imei, phone, c)
      if (!res?.token) throw new Error('No token returned')
      setCreds({ imei, token: res.token }, !!remember)
      creds.set({ imei, token: res.token })
      statusLine.set('Signed in')
      dispatch('signedin')
    } catch (e) {
      statusLine.set(`Verify failed: ${e.message}`)
    } finally {
      verifying = false
    }
  }

  function editPhone() {
    imei = ''
    code = ['', '', '', '', '', '']
    step = 'phone'
  }
</script>

<div class="auth-panel">
  <h2>Sign in</h2>

  {#if step === 'phone'}
    <div class="auth-step">
      <label>
        Phone
        <input type="tel" bind:value={phone} placeholder="05XXXXXXXX" inputmode="tel" autocomplete="tel" />
      </label>
      <button class="btn primary" on:click={() => onSendOtp(false)} disabled={sending}>Send code</button>
    </div>
  {:else}
    <div class="auth-step">
      <p class="muted">Enter the 6-digit code sent to <strong>{phone}</strong></p>
      <div class="otp-grid" role="group" aria-label="One-time code">
        {#each [0,1,2,3,4,5] as i}
          <input bind:value={code[i]} inputmode="numeric" pattern="[0-9]*" maxlength="1" />
        {/each}
      </div>
      <div class="auth-row">
        <label class="remember">
          <input type="checkbox" bind:checked={remember} /> Remember me
        </label>
      </div>
      <div class="auth-actions">
        <button class="btn primary" on:click={onVerify} disabled={verifying}>Verify</button>
        <button class="btn secondary" on:click={() => onSendOtp(true)} disabled={!!resendTimerId}>Resend</button>
        <span class="muted">{resendText}</span>
      </div>
      <div class="auth-links">
        <button class="linklike" type="button" on:click={editPhone}>Edit phone</button>
      </div>
    </div>
  {/if}
</div>
